#!/bin/bash
# Installs tmux and sets up its configuration.

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TMUX_CONF="$HOME/.tmux.conf"

ensure_link "$THIS_DIR/main.conf" "$TMUX_CONF"
ensure_package tmux

TMUX_DIR="$HOME/.tmux"
