#!/bin/bash
#
# Installs everything necessary for my command-line dev environment.

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$BASE_DIR/common.sh"

# We need git from the git-go
ensure_package "git"

# Create our lovely Developer directory
mkdir -p "$DEV_DIR"

# Run installers
install
