#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VIM_DIR="$HOME/.vim"

# Symlink our vim config
ensure_link "$THIS_DIR" "$VIM_DIR"

mkdir -p "$VIM_DIR/tmp"

# node is for vim-prettier's npm install step and ALE's eslint/prettier fixers.
ensure_package vim node

if [ ! -f "$VIM_DIR/autoload/plug.vim" ] ; then
    if missing "curl"; then
        $grab curl
    fi

    curl -fLo "$VIM_DIR/autoload/plug.vim" --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# need ag for CtrlP
ensure_package "the_silver_searcher"

# install all of our plugins
vim -c :PlugInstall -c :qa
